### ISSUE TITLE
MySQL connection error 

### ISSUE THREAD

**Issue by DeVerMyst** [malatia/Brief_db_final#1]
(.venv) (base) ➜  Brief_db_final git:(main) ✗ python3 db_create.py       
Traceback (most recent call last):
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
    with util.safe_reraise():
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/db_create.py", line 112, in <module>
    main()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/db_create.py", line 107, in main
    Base.metadata.create_all(engine)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3116, in _run_ddl_visitor
    with self.begin() as conn:
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3032, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
    with util.safe_reraise():
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/antonyschutz/Documents/SIMPLON/BRIEF_RENDU/Brief_db_final/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by DeVerMyst** [comment]
problem solved
